### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by dev-binhnx** [cyco130/vavite#78] opened 2023-11-01 17:11 UTC
![image](https://github.com/cyco130/vavite/assets/124752273/22cce942-c009-46e4-8e53-eba4aca02402)

**Comment by cyco130** [comment] 2023-11-05 18:24
Can you provide a reproduction? I don't understand much from the attached screenshot.

**Comment by cyco130** [comment] 2023-12-30 20:45
Closing due to lack of reproduction.

**Closed by cyco130** 2023-12-30 20:45 UTC
