### ISSUE TITLE
Vite shouldn't crash or silently fail

### ISSUE THREAD

**Issue by YPetremann** [cyco130/vavite#19] opened 2023-01-04 13:21 UTC
One thing that is a burden is that when developping, sometimes the server silently fail, then I restart it and I found that it completely crash, so in the debug process I have to check if it's not silently failing and manually restart the server each times it continue to crash. 

What it should do is that whenever there is an error, it should simply display the error and wait for the next change, even if it occurs at startup.

**Comment by cyco130** [comment] 2023-01-04 14:04
Are you using the server entry or the handler entry. I recently introduced a change that fixes this fir the handler entry. It might have made things worse for server entry.

**Comment by cyco130** [comment] 2023-01-14 15:55
Closing this because I can't reproduce it. Feel free to reopen with a reproduction.

**Closed by cyco130** 2023-01-14 15:55 UTC
